### ISSUE TITLE
ONE staking

### ISSUE THREAD

**Issue by Rogerkap** [xChickens/xChickens#3]
I'm not that experienced in crypto staking.  I have my ONE at binance.us which discontinued ONE staking.  Do I send my ONE to one of the crypto wallets that I have, e.g., MetaMask, or what do I need to do to stake with you?

If I stake with you, is the crypto considered being held in the U.S.?  I assume you issue a 1099 for tax purposes. Does the 1099 come from a U.S. address?  I need to report any non-US assets being held at an institution outside of the U.S.  Thanks.

**Comment by xChickens** [comment]
All you need to do is stake at the harmony website at https://staking.harmony.one/

You can either use the Harmony official wallet extension, or MetaMask, or any of the other supported wallets.

Staking on my validator wouldn't be considered in the U.S., all the validators are essentially international. There's no way that the IRS could even necessarily link whatever address I'm using back to my actual persons. I wouldn't issue any kind of 1099, and I don't think any other validator would either.

You would probably only get taxed if you were liquidating from crypto to fiat currency. Otherwise, any decentralized transaction probably wouldn't be taxed.
